image: archlinux
secrets:
- 72c9ab0b-ed5f-4291-bab7-30b361be94a6
packages:
  - go
sources:
  - https://github.com/go-ap/auth
environment:
  GO111MODULE: 'on'
tasks:
  - tests: |
      cd auth
      make test
  - coverage: |
      set -a +x
      cd auth && make coverage
      GIT_SHA=$(git rev-parse --verify HEAD)
      GIT_BRANCH=$(git name-rev --name-only HEAD)
      source ~/.code-cov.sh
      curl -X POST \
          --data-binary @auth.coverprofile \
           -H 'Accept: application/json' \
          "https://codecov.io/upload/v2?commit=${GIT_SHA}&token=${AUTH_TOKEN}&branch=${GIT_BRANCH}&service=custom" || true
