image: archlinux
packages:
  - go
sources:
  - https://github.com/go-ap/auth
environment:
  GO111MODULE: 'on'
tasks:
  - tests: |
      cd auth
      make test
  - coverage: |
      set -a +x
      cd auth && make coverage
      GIT_SHA=$(git rev-parse --verify HEAD)
      GIT_BRANCH=$(git name-rev --name-only HEAD)
