package auth

import (
	"crypto/ecdsa"
	"crypto/ed25519"
	"crypto/rsa"
	"net/http"
	"sync"
	"time"

	"github.com/common-fate/httpsig/alg_ecdsa"
	"github.com/common-fate/httpsig/alg_ed25519"
	"github.com/common-fate/httpsig/alg_rsa"
	"github.com/common-fate/httpsig/sigbase"
	"github.com/common-fate/httpsig/sigparams"
	"github.com/common-fate/httpsig/sigset"
	rfc "github.com/common-fate/httpsig/verifier"
	vocab "github.com/go-ap/activitypub"
	"github.com/go-ap/errors"
)

type syncedNonceStore struct {
	sync.Map
}

func (s *syncedNonceStore) Seen(n string) bool {
	_, ok := s.Map.LoadOrStore(n, struct{}{})
	return ok
}

var nonceStore = new(syncedNonceStore)

func timeNow() time.Time {
	return time.Now().Truncate(time.Second).UTC()
}

var nowFn = timeNow

// TODO(marius): have DEV/non-DEV versions
var defaultValidationOpts = sigparams.ValidateOpts{
	ForbidClientSideAlg:       false,
	BeforeDuration:            time.Minute,
	RequiredCoveredComponents: map[string]bool{},
	RequireNonce:              true,
}

// VerifyRFCSignature checks for RFC9421 compatible HTTP signatures.
// It is based on the common-fate/httpsig/verifier.Parse functionality adapted for go-ap.
func (k httpSigVerifier) VerifyRFCSignature(req *http.Request) (vocab.Actor, error) {
	if req == nil {
		return AnonymousActor, nil
	}
	if len(req.Header) == 0 {
		return AnonymousActor, nil
	}

	ctx := req.Context()
	now := nowFn()

	// Parse the Signature and Signature-Input fields as described in Sections 4.1 and 4.2,
	// and extract the signatures to be verified and their labels.
	set, err := sigset.Unmarshal(req)
	if err != nil {
		return AnonymousActor, err
	}

	errs := make([]error, 0, len(set.Messages))
	defOpts := defaultValidationOpts
	// NOTE(marius): in the original the verifier requires the value of the Tag that
	// the signature has been generated with to extract the correct one from the headers.
	// But I can't think of a way in which this would be useful in our case as
	// we're planning to accept signatures generated by multiple implementations, not just ours.
	//
	// So for our code, we just iterate over the signatures, if multiple exist, and exit
	// on first success, or all failures.
	for _, msg := range set.Messages {
		// Validate the signature params.
		if err = msg.Input.Validate(defOpts, now); err != nil {
			errs = append(errs, err)
			continue
		}

		// Validate the nonce has not been seen before.
		if seen := nonceStore.Seen(msg.Input.Nonce); seen {
			errs = append(errs, errors.Newf("nonce has already been seen"))
			continue
		}

		// Find the key associated with the Key ID.
		//
		//  Start with the set of allowable algorithms known to the application. If any of the
		// following steps select an algorithm that is not in this set, the signature validation fails.
		//
		// 6.2. If the algorithm is known through external means such as static configuration or
		// external protocol negotiation, the verifier will use that algorithm.
		//
		// 6.3. If the algorithm can be determined from the keying material, such as through an
		// algorithm field on the key value itself, the verifier will use that algorithm.
		//
		// 6.4. If the algorithm is explicitly stated in the signature parameters using a value
		// from the "HTTP Signature Algorithms" registry, the verifier will use the referenced algorithm.
		actor, aKey, err := k.loader.loadKey(msg.Input.KeyID)
		if err != nil {
			errs = append(errs, err)
			continue
		}

		key, err := toCryptoPublicKey(*aKey)
		if err != nil {
			errs = append(errs, err)
			continue
		}
		var alg rfc.Algorithm
		switch pk := key.(type) {
		case *rsa.PublicKey:
			alg = alg_rsa.NewRSAPSS512Verifier(pk)
		case *ecdsa.PublicKey:
			alg = alg_ecdsa.P384{PublicKey: pk}
		case ed25519.PublicKey:
			alg = alg_ed25519.Ed25519{PublicKey: pk}
		}

		// 6.5. If the algorithm is specified in more than one location (e.g., a combination of static
		// configuration, the algorithm signature parameter, and the key material itself), the resolved
		// algorithms MUST be the same. If the algorithms are not the same, the verifier MUST fail the verification.
		if msg.Input.Alg != "" && msg.Input.Alg != alg.Type() {
			errs = append(errs, errors.Newf("invalid algorithm signature parameter: wanted %q but got %q", alg.Type(), msg.Input.Alg))
			continue
		}

		// Use the received HTTP message and the parsed signature parameters to recreate the
		// signature base, using the algorithm defined in Section 2.5. The value of the
		// @signature-params input is the value of the Signature-Input field
		// for this signature serialized according to the rules described in Section 2.3.
		//
		// Note that this does not include the signature's label from the Signature-Input field.
		base, err := sigbase.Derive(msg.Input, nil, req, alg.ContentDigest())
		if err != nil {
			errs = append(errs, errors.Annotatef(err, "recreating signature base"))
			continue
		}

		stringToSign, err := base.CanonicalString(msg.Input)
		if err != nil {
			errs = append(errs, errors.Annotatef(err, "recreating string to sign"))
			continue
		}

		// Verify the signature using the provided algorithm.
		if err = alg.Verify(ctx, stringToSign, msg.Signature); err != nil {
			errs = append(errs, errors.Annotatef(err, "verifying signature"))
			continue
		}
		return actor, nil
	}

	return AnonymousActor, errors.Annotatef(errors.Join(errs...), "no matching signatures")
}
